# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea299922fe684e6591766d07bfd77efe02fc4350d921ffcb91b5632410a1a6b377ede0b44cd635275f81e5f228aca9ae694aff9b738b9dd0eec736b2a9116693
  meet_up_key: '430473354567f7a2917273b48793a'

test:
  secret_key_base: 9bfa54a65d6b800dcc5a028f6e2996b1559af3c3a6746de013e40319b184fcae7479ab9c780522ed0b6d66b42cb431275ecd3d6ba22512b6dfdfee124a3dec82
  meet_up_key: '430473354567f7a2917273b48793a'
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
